planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: True
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: true
      allow_unknown: true
      visualize_potential: false
      use_dijkstra: true
      use_quadratic: true
      use_grid_path: true
      old_navfn_behavior: false
      default_tolerance: 0.0
      lethal_cost_threshold: 253
      neutral_cost: 50
      cost_factor: 3.0
      publish_potential: true
      orientation_mode: 0
      orientation_window_size: 1.0
      
global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 2.0  # Change from 1.0 to 2.0
      publish_frequency: 2.0  # Change from 1.0 to 2.0
      global_frame: map
      robot_base_frame: base_footprint  # Change from base_link to base_footprint
      transform_tolerance: 0.5  # Add transform_tolerance parameter
      use_sim_time: True
      # footprint: []
      # footprint_padding: 0.01
      robot_radius: 0.3  # Change from 0.175 to 0.3
      resolution: 0.05  # Change from 0.06 to 0.05
      track_unknown_space: true
      always_send_full_costmap: false  # Change from true to false
      rolling_window: false  # Add rolling_window parameter
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan_source
        scan_source:
          topic: /scan
          max_obstacle_height: 1.0  # Change from 2.0 to 1.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 3.0
          raytrace_min_range: 0.0
          obstacle_max_range: 2.5
          obstacle_min_range: 0.0
          inf_is_valid: false  # Add inf_is_valid parameter
        track_unknown_space: false
        footprint_clearing_enabled: true
        combination_method: 1
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        unknown_cost_value: -1
        lethal_cost_threshold: 100
        map_topic: /map
        track_unknown_space: true
        use_maximum: false
        trinary_costmap: true 

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 30.0  # Change from 4.0 to 30.0
        inflation_radius: 0.45
